### ISSUE TITLE
Trace chain element slows down NSM significantly

### ISSUE THREAD

**Issue by NikitaSkrynnik** [networkservicemesh/sdk#1182] opened 2021-11-30 07:56 UTC
## Current Behavior

`log.EnableTracing(true)` slows down tests by two or three times

## Failure Logs

https://github.com/networkservicemesh/sdk/runs/4364126725?check_suite_focus=true#step:5:613

**Comment by edwarnicke** [comment] 2021-12-01 14:57
@NikitaSkrynnik 

I'm pretty sure this is the root of our problem:

https://github.com/networkservicemesh/sdk/blob/e33b665d2e98196dd3b1a49d875b528c2f78bfce/pkg/tools/log/spanlogger/spanlogger.go#L43-L43

Its effectively a *global* lock on the entire system via the spanlogger... we should solve our race condition problem *without* such a global lock.

**Comment by NikitaSkrynnik** [comment] 2021-12-02 12:51
@edwarnicke Yes, thank you. We also found out that [Diff](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/core/trace/common.go#L74) function takes a lot of time when we enable tracing. We tried to replace it with Diff function from [go-cmp](https://github.com/google/go-cmp) package but it only got worse.

We also investigated test time with different settings. We used only one test [Test_PassThroughRemoteUsecase](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/chains/nsmgr/suite_test.go#L403). Here are the results:
- no race flag, no tracing -  0.648s
- race flag, no tracing -  5.83s
- no race flag, tracing -  6.56s
- race flag, tracing -  60.85s
- race flag, tracing (no `io.Discard`) - 72.83s
- race flag, tracing (no `io.Discard`, no `Diff function`) - 23.52s
- no race flag, tracing (no `io.Discard`) - 7.36s
- no race flag, tracing (no `io.Discard`, `Diff function` from [go-cmp](https://github.com/google/go-cmp)) - 99s

The first four tests were launched with `logruslogger.SetOutput(io.Discard)`

**Comment by edwarnicke** [comment] 2021-12-02 14:59
Ah... good analysis... thoughts on how to proceed?

**Comment by NikitaSkrynnik** [comment] 2021-12-03 14:05
I've discussed it with my team. We don't have any solutions now :(

**Comment by edwarnicke** [comment] 2021-12-03 15:03
@NikitaSkrynnik Question: How many times are we running the Diff in the course of the passthrough test?  And have we benchmarked the diff as a single function to see what it's normal costs are?  Even if Diff is taking 10ms to run (a very long time) 60s would entail nearly 60k calls to it... something feels off here.  I can't put my finger on it... but I don't feel like just blaming Diff is the full answer?

Also, have you looked at doing away with the global mutex in our logging... that's a huge huge issue that needs fixing.

**Comment by denis-tingaikin** [comment] 2021-12-07 14:05
@edwarnicke Actually we found that the problem is reproducible only and only with `-race` flag. 

As @NikitaSkrynnik  found the function Diff is working in a few ms without `-race` flag, but with flag`-race` function `Diff` gonna be super slow.

I'm going to close this issue because we don't want to disable `-race` flag. So for this moment, we'll not use full logging on ci (e.g. Diff is disabled for now)

## Conclution

Do not use `Diff` for tests with flag `-race` as we do currently for the main branch.

@edwarnicke Be free to reopen this if you still have any open questions.

**Closed by denis-tingaikin** 2021-12-07 14:05 UTC
Labels: bug
