### ISSUE TITLE
checkid registry chain element is incorrectly work in case of restart nsmgr.

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#1099] opened 2021-10-10 09:13 UTC
## Expected Behavior

We should allow registration from nsmgr that was restarted or for which has been changed network configuration.

## Current Behavior

old registrations always fail if nsmgr changed IP.

## Failure Information (for bugs)

[nse (1).txt](https://github.com/networkservicemesh/sdk/files/7317168/nse.1.txt)

## Steps to Reproduce

1. start nsm setup
2. start nse with ns1
3. start client to ns1
4. restart nsmgr
5. see at logs of nse

## Potential solutions

1. Remove checkid.
2. Make this working https://github.com/networkservicemesh/sdk/blob/ec235de055f10ca080dcfd34e06d094d27806b8b/pkg/registry/common/setid/client.go#L56

**Comment by denis-tingaikin** [comment] 2021-10-10 09:14
@Bolodya1997 thoughts?

**Comment by Bolodya1997** [comment] 2021-10-11 03:07
> @Bolodya1997 thoughts?

It is a duplicate of https://github.com/networkservicemesh/sdk/issues/1079.

**Comment by denis-tingaikin** [comment] 2021-10-11 05:46
I don't see solutions in https://github.com/networkservicemesh/sdk/issues/1079

**Closed as completed** 2021-10-12 03:23 UTC
Labels: bug
