### ISSUE TITLE
Nested serialize.Executor.AsyncExec calls may deadlock when overwhelmed

### ISSUE THREAD

**Issue by xzfc** [networkservicemesh/sdk#512] opened 2020-10-08 02:26 UTC
Example of code that deadlocks:
```go
func TestDeadlock(t *testing.T) {
        var exec serialize.Executor

        exec.AsyncExec(func() {
                time.Sleep(time.Second)
                exec.AsyncExec(func() {})
        })

        for i := 0; i < 105; i++ { // 105 is a number that slightly more than channelSize
                exec.AsyncExec(func() {})
        }

        <-exec.AsyncExec(func() {})
}
```
The issue is that `AsyncExec()` may block on [channel write](https://github.com/networkservicemesh/sdk/blob/cf9c2259e946f48d65c4e4f44e8a283e239ebb50/pkg/tools/serialize/serialize.go#L63).

We have code that uses nested `AsyncExec()` and thus may potentially deadlock:
* https://github.com/networkservicemesh/sdk/blob/cf9c2259e946f48d65c4e4f44e8a283e239ebb50/pkg/networkservice/connectioncontext/dnscontext/client.go#L107

We should either document this limitation and rewrite the code that uses nested `AsyncExec()` OR rework `serialize.Executor` to support unlimited nested calls.

**Comment by denis-tingajkin** [comment] 2020-10-08 04:28
Tested locally it is reproducible.
Note: This dead local can be achieved in the real world only by **Server** chain elements which can receive in one moment 100(channelSize) or more requests.

**Comment by denis-tingajkin** [comment] 2020-10-08 04:34
To fix the issue we can use a concurrent queue instead of channel.

**Comment by denis-tingajkin** [comment] 2020-10-13 16:10
@edwarnicke , @haiodo 

I've found additional deadlock with executor:
```
func TestDeadlock2(t *testing.T)  {
	e := serialize.Executor{}
	e.AsyncExec(func() {
		time.Sleep(time.Millisecond * 100)
		<-e.AsyncExec(func() {
		})
	})
	<-e.AsyncExec(func() {
		logrus.Info("Deadlock")
	})
}
```

It looks like we need to fully rework ` serialize.Executor` to support this kind scenario. Thoughts?

**Comment by edwarnicke** [comment] 2020-10-13 16:43
I don't think the issue in this one is calling AsyncExec inside AsyncExec ... its *blocking* on the nested AsyncExec call.  And yes, that's one probably best addressed by documentation.

**Closed** 2020-10-20 14:45 UTC
Labels: bug, good first issue
